project:
  type: website
  output-dir: _site
  resources:
    - figures/  

website:
  navbar:
    left:
      - href: hw02_1.html
        text: "1부"
      - href: hw02_2.html
        text: "2부"

format:
  html:
    embed-resources: true
  ipynb: default  # HTML 빌드 시 ipynb 파일도 함께 생성하도록 설정
